### PR TITLE
created seed files for application and installed dependencies

### PR DESCRIPTION
**Pull request by kirkwgraves**
I created the basic seed files we'll need to get the application started and installed the key dependencies we've discussed using (Angular Material, UI Bootstrap, etc).

@jcockhren 
@maxamad13

### CODE REVIEW

**Comment by jtmp2r** [comment]
Gotcha! Not sure how to do the thumbs up.

**Comment by AdamSheaffer** [comment]
Will you guys absolutely need bootstrap and material design? They might butt heads at some point. If you do, that's cool, but remember you'll need bootstrap's css in your index too since it's a dependency for ui-bootstrap. Other than that, this looks great. :+1:

**Comment by kirkwgraves** [comment]
@AdamSheaffer - Good point! The reason we downloaded UI Bootstrap was for a specific feature (the Typeahead directive already built in); we thought it might be easier to use that directive rather than the typeahead.js plugin (which is a jQuery plugin and looks kind of messy). Which do you recommend? @maxamad13 also noted that Angular Material has an `autocomplete` directive which may do the same thing, in which case we definitely wouldn't need UI Bootstrap. Thx!

**Comment by kirkwgraves** [comment]
@AdamSheaffer @jtmp2r @maxamad13 - It looks `md-autocomplete` is exclusively for drop-downs containing finite lists to aid the user's search; very different from the kind of robust typeahead we're hoping to use for the app. @AdamSheaffer, the docs for the [Typeahead directive in UI-Bootstrap](http://angular-ui.github.io/bootstrap/#/typeahead) say that it's well-integrated with AngularJS. Hoping we can get it working!

**Pull request closed without merging**
